### ISSUE TITLE
Unable to SSH in without fish extension.

### ISSUE THREAD

**Issue by peterwilsoncc** [Chassis/Chassis#1013]
Since #1005 I am unable to ssh in, I am seeing the following in the command line:
```
$vagrant ssh
bash: line 1: fish: command not found
Connection to 127.0.0.1 closed.
```

Checking out 796ededf63314070a54d1cdac1266dc20d9f4230 resolves the issue.

I am using ZSH as my shell with oh-my-zsh installed in case that has any effect.

----

1. What operating system do you use? macOS

2. What version of Vagrant are you running? 2.3.0

3. Are you using VirtualBox or VMWare and which version are you using? VirtualBox

4. Do you have a custom YAML file? If so, what does it contain?
```yaml
# Domain names to use for Vagrant
#
# The first name will be used as the machine's name, subsequent names will be
# aliased in your hosts file and in nginx
#
# (When overriding, include vagrant.local if you need it)
hosts:
    - pw-thing.local
    - ms-thing.local
    - two-ms-thing.local
    - vagrant.local

# Single Site
website:
    name: PW Thing Single Site
multisite: No

plugins:
   - query-monitor
   - user-switching

extensions:
  - mailhog
  - chassis/chassis_openssl
  - xdebug

# Configure ssl to keep the same cert/key
chassis_openssl:
    cert:
        replace: no
    key:
        replace: no

php: 8.1

ip: 192.168.56.31
```

5. Do you have any Chassis other extensions installed? If so, what are they? Mailhog, OpenSSL, xDebug
