### ISSUE TITLE
ngrok now uses the domain *.ngrok-free.app

### ISSUE THREAD

**Issue by peterwilsoncc** [Chassis/Chassis#1029]
ngrok have changed their domain for free accounts to *.ngrok-free.app, therefore setting up a tunnel to a Chassis install results in the default Chassis page rather than the wordpress install.

1. What operating system do you use? macOS

3. What version of Vagrant are you running? 2.3.4

4. Are you using VirtualBox or VMWare and which version are you using? 6.1.36

5. Do you have a custom YAML file? If so, what does it contain?
```yaml
# Domain names to use for Vagrant
#
# The first name will be used as the machine's name, subsequent names will be
# aliased in your hosts file and in nginx
#
# (When overriding, include vagrant.local if you need it)
hosts:
    - xu-classifai.local
    - 2331-124-170-207-170.ngrok-free.app

# Single Site
website:
    name: 10up Classifai
multisite: No

# Multi Site
# website:
#     name: Multisite 10up Classifai
# multisite: Yes
# multisite: subdomains

# Paths
paths:
    base: .
    wp: wp-build
    content: content

plugins:
   - query-monitor
   - user-switching

extensions:
  - mailhog
  - chassis/chassis_openssl
  - phpunit
  - tester
  - xdebug

# Configure ssl to keep the same cert/key
chassis_openssl:
    cert:
        replace: no
    key:
        replace: no

php: 7.4

```

6. Do you have any Chassis other extensions installed? If so, what are they? No
