### ISSUE TITLE
Redirected to a reauthentication URL in multisite

### ISSUE THREAD

**Issue by michaelbeil** [Chassis/Chassis#155]
I am redirected to `http://vagrant.local/wp/wp-login.php?redirect_to=http%3A%2F%2Fvagrant.local%2Fwp%2Fwp-admin%2F&reauth=1` when attempting to login to my local Chassis subdirectory multisite setup.

config.yaml:

``` yaml
# Chassis Configuration
#
# This file is the default configuration for all projects. The fallback order of
# configuration files is:
#
# - project/content/config.local.yaml   (project-specific overrides)
# - project/content/config.yaml         (project-specific defaults)
# - project/config.local.yaml          (global overrides)
# - project/config.yaml                 (global defaults)

# Domain names to use for Vagrant
#
# The first name will be used as the machine's name, subsequent names will be
# aliased in your hosts file and in nginx
#
# (When overriding, include vagrant.local if you need it)
hosts:
    - vagrant.local

# IP address to use on the private network
#
# DHCP is used by default to assign IP addresses dynamically, override only if
# you need a static IP for your box.
#
# Values: "dhcp", or any valid IP
ip: dhcp

# Ubuntu mirror to use during provisioning
#
# Packages are loaded from the built-in Ubuntu repositories, which can be slow
# depending on your location. Override this option to use a local mirror
# instead, which is typically faster.
#
# Can be set to Yes to automatically detect the closest mirror, No to use the
# built-in repositories, or a mirror domain as a string.
#
# Values: Yes, No, or any mirror domain name e.g. http://mirror.optus.net/ubuntu/
apt_mirror: Yes

# Should we use multisite?
# (Only subdirectories are supported currently)
# Values: Yes, No
multisite: Yes

# Database configuration
# (When overriding, include all values)
database:
    name: wordpress
    user: wordpress
    password: vagrantpassword

# Admin configuration
# (When overriding, include all values)
admin:
    user: admin
    email: admin@example.com
    password: password

# WordPress directory
# (This is usually `wp`, unless you're transplanting Chassis into
# an existing project)
wpdir: wp

# PHP version
# Values: 5.3, 5.4, 5.5, 5.6 (or e.g. 5.3.3)
php: 5.4

```

local-config.php:

``` php
<?php

// URL to the content directory
// You'll probably want to change this.
define( 'WP_CONTENT_URL', 'http://' . $_SERVER['HTTP_HOST'] . '/content' );

// Loopback connections can suck, disable if you don't need cron
define( 'DISABLE_WP_CRON', true );

// You'll probably want Automatic Updates disabled during development
define( 'AUTOMATIC_UPDATER_DISABLED', true );

// You'll probably want debug logging during development
define( 'WP_DEBUG_LOG', true );

/* Multisite */
define( 'WP_ALLOW_MULTISITE', true );
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', false);
define('DOMAIN_CURRENT_SITE', getenv('DOMAIN_CURRENT_SITE'));
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);
```

.htaccess:

```
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]

# add a trailing slash to /wp-admin
RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]

RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) $2 [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ $2 [L]
RewriteRule . index.php [L] 
```
