### ISSUE TITLE
Error: Syntax error at 'Hash'; expected ')'

### ISSUE THREAD

**Issue by stuartshields** [Chassis/Chassis#435]
I'm currently updating the vagrant box to see if it fixes the issue. However I'm trying to provision the box and I get the following error:
```
==> default: Error: Syntax error at 'Hash'; expected ')' at /vagrant/puppet/modules/apt/manifests/init.pp:6 on node sc.local
==> default: Error: Syntax error at 'Hash'; expected ')' at /vagrant/puppet/modules/apt/manifests/init.pp:6 on node sc.local
```
Will update this issue if it's been resolved with an update of the box.

1. What operating system do you use?
MacOS Sierra 10.12.6

2. What version of Vagrant are you running?
1.9.7

3. Are you using VirtualBox or VMWare and which version are you using?
VirtualBox

4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)
```
paths:
    base: ..
    content: content
    wp: wordpress
hosts:
    - sc.local
multisite: true

# Define database prefix, since we have tests as well
database:
    name: wordpress
    user: wordpress
    password: vagrantpassword
    prefix: wp_

extensions:
  - chassis/xdebug
```

5. Do you have any Chassis extensions installed? If so, what are they?
- xdebug
- tester
- cavalcade
