### ISSUE TITLE
Unable to install wp profile command

### ISSUE THREAD

**Issue by ericnicolaas** [Chassis/Chassis#436]
I am attempting to install the profile package for wp cli, following these instructions:

https://github.com/wp-cli/profile-command#installing

I noted in #425 that Composer needs to be installed, which I did not have initially. So I added that to my `config.yaml` and ran `vagrant provision`. But no luck. 

Here's the output in terminal:

<img width="503" alt="screenshot 2017-08-18 09 58 03" src="https://user-images.githubusercontent.com/676582/29439267-bcdb976c-83fb-11e7-96fb-f48d4bfa5877.png">

(Obviously a couple bugs there in WP, but I don't think those should be related).

I'm on a Mac, running Sierra 10.12.6. Vagrant 1.9.3 and I'm using VirtualBox 5.1.18 (downloading latest version now).

Here's my `config.yaml`:

```
php: 7.1

hosts: 
  - wpcharitable.local

extensions:
  - javorszky/chassis-openssl
  - MailHog
  - SequelPro
  - Composer

database:
    name: wordpress
    user: wordpress
    password: vagrantpassword
    prefix: xao_
```
