### ISSUE TITLE
Vagrant halt prompts for Github username/password

### ISSUE THREAD

**Issue by ericnicolaas** [Chassis/Chassis#437]
This seems to be related to #319. 

When running `vagrant halt`, Chassis kicks off with downloading submodules. The annoying thing is that it's prompting me for my Github details, which I'm guessing means that when the submodule was cloned initially it was over HTTPS versus SSH.

I did not clone the extensions in my box directly; instead, I had them defined in my `config.yaml` before running `vagrant up` the first time.

Config: 

```

php: 7.1

hosts: 
  - wpcharitable.local

extensions:
  - javorszky/chassis-openssl
  - MailHog
  - SequelPro
  - Composer

database:
    name: wordpress
    user: wordpress
    password: vagrantpassword
    prefix: xao_

```

I'm on a Mac, running Sierra 10.12.6. Vagrant 1.9.3 and I'm using VirtualBox 5.1.18 (downloading latest version now).
