### ISSUE TITLE
Add back: Allow overriding VM properties

### ISSUE THREAD

**Issue by TangRufus** [Chassis/Chassis#442]
#283  seems lost in master.

VirtualBox uses default values no matter what you set in config.yaml

```yaml
virtualbox:
    memory: 2048 # ignored
    cpus: 4 # ignored
```
