### ISSUE TITLE
Multisite network admin not available

### ISSUE THREAD

**Issue by joemcgill** [Chassis/Chassis#472]
I've run into an issue a few times where the network admin screen is not available, as if the admin user doesn't have the proper capabilities. The menu for visiting the network admin is not available from the admin menu (see screenshot to follow)

<img width="273" alt="screen shot 2017-11-28 at 4 43 45 pm" src="https://user-images.githubusercontent.com/801097/33348678-e709a504-d45c-11e7-9a48-deaeca645545.png">

If I visit the network admin URL directly, I see a `Sorry, you are not allowed to access this page.` error.

So far, I haven't been able to track down the steps to reproduce this issue, and others sharing the same config don't seem to be experiencing this problem.

1. What operating system do you use? Mac OS 10.13.1

2. What version of Vagrant are you running? 2.0.1

3. Are you using VirtualBox or VMWare and which version are you using? VB 5.1.30 r118389 (Qt5.6.3)

4. Do you have a custom YAML file? If so, what does it contain?

```
paths:
    base: ..
    content: content
    wp: wordpress
hosts:
    - main.local
    - site1.main.local
    - site2.main.local
multisite: subdomains

# Define database prefix, since we have tests as well
database:
    name: wordpress
    user: wordpress
    password: vagrantpassword
    prefix: wp_
# Define the extensions we want
extensions:
    - chassis/xdebug
    - chassis/tester
    - chassis/sequelpro
    - chassis/cavalcade
    - chassis/mailhog
    - chassis/memcache
    - chassis/phpcs
```

5. Do you have any Chassis extensions installed? If so, what are they? (see above)
