### ISSUE TITLE
Cannot log in to WP admin when using nested local checkout of WP trunk

### ISSUE THREAD

**Issue by kadamwhite** [Chassis/Chassis#506]
1. What operating system do you use?

Ubuntu 17.10

2. What version of Vagrant are you running?

2.0.2

3. Are you using VirtualBox or VMWare and which version are you using?

VirtualBox 5.1.30_Ubuntu

4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)

```
paths:
    # Use the Chassis box normally...
    base: .
    # But use my development copy of WordPress for the source
    content: git/src/wp-content
    wp: git/src

# Also use your development copy of WordPress for the unit test
# framework, and for the unit tests themselves
synced_folders:
    git: /vagrant/extensions/tester/wpdevel

# Set the host to `core.local` to distinguish from other chassis boxes
hosts:
    - core.local

# Explicitly set database configuration to avoid warning with Tester
database:
    name: wordpress
    user: wordpress
    password: vagrantpassword
    prefix: wp_

extensions:
    - Chassis/Tester
    - Chassis/XDebug

# Run in multisite mode (totally optional)
multisite: false

# XDebug IDE key
ide: VSCODE
```

5. Do you have any Chassis extensions installed? If so, what are they?

XDebug & Tester

-------------------------------------------

The above config reflects that I've checked out the WordPress `git://develop.git.wordpress.org/` repo as `./git`, with the intent of doing core development. I had the core repo running perfectly within Chassis using [the core dev setup steps](http://docs.chassis.io/en/latest/guides/#wordpress-core-development), but I couldn't figure out how to get xdebug's path mapping set up in VSCode _or_ PHPStorm with the sibling directories so I gave up and tried cloning the dev repo inside the chassis directory instead.

When I `vagrant up` with the above, providing I've followed the wp-config modification steps outlines in the core setup guide, the site comes up properly. However, `core.local/wp-admin` just displays the front page of the site, and `core.local/git/src/wp-admin` displays the login form but will not actually log me in.

My goal is not _per se_ to resolve this specific issue. What I want is to be able to run XDebug on a copy of WP core trunk, running within Chassis. If there's a better way to accomplish this, I'm all ears!
