### ISSUE TITLE
Multisite Subsite Hosts not getting written to hosts file

### ISSUE THREAD

**Issue by mikeselander** [Chassis/Chassis#510]
After spinning up a box, I am attempting to create several subsites using WP CLI in Chassis SSH. The sites are created perfectly, but the hosts file with the box is not getting rewritten host names after updating a site. It appears to me that the filters (which should be actions technically btw) are not running properly.

Thanks!

**Example site setup run:**
`vagrant ssh -c "wp site create --slug=gb && wp language core install en_GB --url=http://gb.clientname.local"`

1. What operating system do you use?
Mas OS-X

2. What version of Vagrant are you running?
2.0.3 

3. Are you using VirtualBox or VMWare and which version are you using?
Virtualbox

4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)
```
# Domain names to use for Vagrant
#
# The first name will be used as the machine's name, subsequent names will be
# aliased in your hosts file and in nginx
#
# (When overriding, include vagrant.local if you need it)
hosts:
  - clientname.local

# Should we use multisite?
multisite: subdomains

# Set database values to save the prefix so Chassis doesn't freak out on
# re-provisions after tests.
database:
    name: wordpress
    user: wordpress
    password: vagrantpassword
    prefix: wp_

# Themes
#
# Install a list of themes, and activate the last one of them
themes:
  - my_theme

# Extensions
#
# Install a list of extensions automatically
extensions:
  - Chassis/Tester
  - Chassis/db-backup
  - Chassis/Xdebug

# PHP version
php: 7.2

# Run database saves on vagrant halts
db-backup:
  halt: yes
  suspend: no

```

5. Do you have any Chassis extensions installed? If so, what are they?
Yes, see above.
