### ISSUE TITLE
Configuration files in non-standard `content` directory ignored

### ISSUE THREAD

**Issue by mikeselander** [Chassis/Chassis#581]
When using a non-standard content directory, Chassis configuration files in said directories are not parsed, and the configuration files are only evaluated against the default content folder.

Consider the following project setup (common hm-base type setup):
```
 - /chassis (Everything Chassis)
   - config.local.yaml (Basic overrides (see full file below)
 - /content (Actual used content directory)
   - config.local.yaml (Installation-specific overrides)
 - /wordpress (WordPress used on platform)
```

and the following paths:
```yml
paths:
  base: ..
  content: content
  wp: wordpress
```

If one were to run an installation with the above configuration files, the `/content/config.local.yaml` would get ignored. It's only after adding a `/chassis/content` directory and adding the config file to _that_ directory that the customizations would take effect.

I would expect that Chassis would take a look at `chassis/config.local.yaml` (since this should always be in the same place, it seems, and if there is a custom content path set, load the _custom_ content directory configuration files as opposed to the default Chassis one.

1. What operating system do you use?
Mas OS X 10.13.6

2. What version of Vagrant are you running?
2.1.5

3. Are you using VirtualBox or VMWare and which version are you using?
Virtualbox 5.2.18

4. Do you have a custom YAML file? If so, what does it contain?
```
# Establish our custom paths for local.
paths:
  base: ..
  content: content
  wp: wordpress

# Default domain to known.
hosts:
  - client.local

# Define database prefix, since we have tests as well.
database:
  name: wordpress
  user: wordpress
  password: vagrantpassword
  prefix: wp_

# Install a list of Chassis extensions automatically.
extensions:
  - Chassis/Cavalcade
  - Chassis/Debugging
  - Chassis/Memcache
  - Chassis/SequelPro
  - Chassis/Tester
  - Chassis/Xdebug

# PHP version.
php: 7.0

# Setup a predictable administrator to begin with.
admin:
  user: clientdev
  email: admin@example.com
  password: password

# Default our theme activated and turned on.
themes:
  - client
```

5. Do you have any Chassis extensions installed? If so, what are they?
*See above*
