### ISSUE TITLE
`Class[Apt] is already declared` bug

### ISSUE THREAD

**Issue by mikeselander** [Chassis/Chassis#601]
#600 is now causing an error when provisioning on a new box. I receive the following error twice:

`Error: Duplicate declaration: Class[Apt] is already declared; cannot redeclare at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/development.pp:26 on node client.local`

After manually reverting this back to the one-liner, the box sets up correctly.

1. What operating system do you use?
Mac OS X 10.14.2

2. What version of Vagrant are you running?
2.2.2

3. Are you using VirtualBox or VMWare and which version are you using?
Virtualbox 5.2.22

4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)

```
paths:
    base: ..
    content: content
    wp: wordpress
hosts:
    - client.local
    - motogp.client.local
    - ...
multisite: subdomains

# Define database prefix, since we have tests as well
database:
    name: wordpress
    user: wordpress
    password: vagrantpassword
    prefix: wp_
# Define the extensions we want
extensions:
    - chassis/xdebug
    - chassis/tester
    - chassis/sequelpro
    - chassis/cavalcade
    - chassis/mailhog
    - chassis/memcache
    - chassis/phpcs
    - chassis/chassis-elasticsearch
    - chassis/tachyon
# Set PHP version to 7.2 to align with hosting
php: 7.2
# Increase ES memory limit to avoid crashes
elasticsearch:
  jvm_options:
    - '-Xms512m'
    - '-Xmx512m'
```
