### ISSUE TITLE
Can't activate user's account in a multisite

### ISSUE THREAD

**Issue by Simek11** [Chassis/Chassis#615]
I wanted to test a multisite in Chassis and I was able to enable it but I have a problem with activating users' accounts.

As a super admin I allowed site administrators to add new users. Then as a site administrator I added a new user and I got an activation email. I opened the email in MailHog and tried to click the activation link which looks like this `http://wordpress.test/site3/wp-activate.php?key=b5a5f9162d8097f9` but I get the error `Registration has been disabled`.

I tried to enable registration but it didn't help me at all. When registration is enabled I get the registration form after I click an activation link in MailHog.

What can be the reason of this problem? Is there any chance to activate user's account manually?

**Comment by BronsonQuick** [comment]
Hey @Simek11, thanks for logging and issue. I'm currently trying to replicate it now for you.

In terms of the users that aren't activated you should be able to install [Unconfirmed](https://wordpress.org/plugins/unconfirmed/) to activate those users.

I also have a few questions. I noticed the URL you posted has `http://wordpress.test` rather than `http://wordpress.local`. The `.local` domain is what Chassis normally uses it.

Can you please answer the following questions for me:

1. What operating system do you use?

2. What version of Vagrant are you running?

3. Are you using VirtualBox or VMWare and which version are you using?

4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)

5. Do you have any Chassis extensions installed? If so, what are they?

6. Do you have any plugins installed that aren't in your custom YAML file?

Hopefully if I can't replicate your issue now I'll be able to replicate it after I've got a little bit more information. Thanks!

**Comment by BronsonQuick** [comment]
Hey @Simek11, I wasn't able to replicate this issue with a Chassis WordPress multisite with a subfolder setup and following the other instructions you mentioned so please get back to me with answers to my questions and we'll go from there! Thanks!

**Comment by Simek11** [comment]
Thank you for your response. Yes I changed default `.local` domain to `.test`. There is no special reason of that. I checked what happens if I change domain back to `.local`.  I'm still having the same problem.

I'm answering your questions.

1. My operating system is macOS Mojave 10.14.4.
2. Vagrant's version is 2.2.4.
3. I use VirtualBox 5.2.28
4. I put my configuration in the `config.local.yaml` file:
```
hosts:
    - wordpress.test

ip: 192.168.33.11

multisite: yes

database:
    name: wordpress
    user: wordpress
    password: wordpress
    prefix: wp_

admin:
    user: admin
    email: admin@example.com
    password: admin

extensions:
    - nodejs
    - npm
    - Composer
    - Gulp
    - MailHog
    - SequelPro
    - phpini
    - Xdebug

php: 5.6

virtualbox:
    memory: 512
    cpus: 1
```
5. Extensions are listed above.
6. I don't have any plugins.

Thank you very much for mentioning _Unconfirmed_ plugin. This workaround works fine for me.
