### ISSUE TITLE
Chassis Extensions update check runs when running Grunt

### ISSUE THREAD

**Issue by ntwb** [Chassis/Chassis#745]
When running `grunt phpunit` as Vagrant SSH's into Chassis Chassis runs the extensions update:

```shell
❯ grunt phpunit:workflow
Running "phpunit:workflow" (phpunit) task
/Users/netweb/Code/HumanMade/my-repo
Logging into vagrant...
Checking for Chassis extension updates...
```

It shouldn't run these checks at this point in time

1. What operating system do you use?
MacOS
2. What version of Vagrant are you running?
Vagrant 2.2.5
3. Are you using VirtualBox or VMWare and which version are you using?
VirtualBox 6.0.12
4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)
```yaml
paths:
  base: ..
  content: content
  wp: wordpress

hosts:
  - my.local
multisite: true

# Define database prefix, since we have tests as well
database:
  name: wordpress
  user: wordpress
  password: vagrantpassword
  prefix: wp_
# Define the extensions we want
extensions:
  - chassis/xdebug
  - chassis/sequelpro
  - chassis/cavalcade
  - chassis/composer
  - chassis/phpcs
  - chassis/mailhog
  - chassis/chassis-elasticsearch
  - chassis/intl
  - chassis/tester
  - chassis/phpini
  - chassis/nodejs
  - chassis/npm
elasticsearch:
  version: '5.3.3'
  jvm_options:
    - '-Xms1024m'
    - '-Xmx1024m'
composer:
  paths:
    - /chassis/content/plugins-mu/vendor/memcached-adapter
    - /chassis/content/plugins-mu/vendor/simple-cache-bridge
    - /chassis/content/plugins-mu/vendor/PhpSpreadsheet
php: 7.2
virtualbox:
    memory: 8192
    cpus: 3
```
5. Do you have any Chassis other extensions installed? If so, what are they?
