### ISSUE TITLE
Chassis Extensions not updating

### ISSUE THREAD

**Issue by ntwb** [Chassis/Chassis#746]
When Chassis is performing extension update check it is unable to update the extension even though it correctly identifies the extensions requires updating.

```shell
Updating nodejs...
The nodejs extension is not on the master branch so we are skipping this update.
If you wish to update the nodejs extension, please run `git checkout master && git pull` inside the root directory of the extension. 
```

The Node.JS Extension is in fact on `master`:
```shell
~/code/humanmade/my-repo/chassis/extensions/nodejs master ⇣
❯ git remote -v
origin  https://github.com/chassis/nodejs (fetch)
origin  https://github.com/chassis/nodejs (push)
```

1. What operating system do you use?
MacOS
2. What version of Vagrant are you running?
Vagrant 2.2.5
3. Are you using VirtualBox or VMWare and which version are you using?
VirtualBox 6.0.12
4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)
```yaml
paths:
  base: ..
  content: content
  wp: wordpress

hosts:
  - my.local
multisite: true

# Define database prefix, since we have tests as well
database:
  name: wordpress
  user: wordpress
  password: vagrantpassword
  prefix: wp_
# Define the extensions we want
extensions:
  - chassis/xdebug
  - chassis/sequelpro
  - chassis/cavalcade
  - chassis/composer
  - chassis/phpcs
  - chassis/mailhog
  - chassis/chassis-elasticsearch
  - chassis/intl
  - chassis/tester
  - chassis/phpini
  - chassis/nodejs
  - chassis/npm
elasticsearch:
  version: '5.3.3'
  jvm_options:
    - '-Xms1024m'
    - '-Xmx1024m'
composer:
  paths:
    - /chassis/content/plugins-mu/vendor/memcached-adapter
    - /chassis/content/plugins-mu/vendor/simple-cache-bridge
    - /chassis/content/plugins-mu/vendor/PhpSpreadsheet
php: 7.2
virtualbox:
    memory: 8192
    cpus: 3
```
5. Do you have any Chassis other extensions installed? If so, what are they?
