### ISSUE TITLE
Site name doesn't reflect `site.name` config value.

### ISSUE THREAD

**Issue by peterwilsoncc** [Chassis/Chassis#904]
Setting the site name in the yaml file isn't reflected when the site is provisioned. The site's is always set to `Chassis Site`.

In `puppet/modules/wp/manifests/site.pp` the relevant setting of `--title='$sitename'` appears correct so I am wondering if the value is been assigned to a different variable name. I am unable to find where the variable is set, sorry.

1. What operating system do you use? macOS Big Sur

2. What version of Vagrant are you running? 2.2.10

3. Are you using VirtualBox or VMWare and which version are you using? VirtualBox 6.1.16

4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)

```yaml
# Domain names to use for Vagrant
#
# The first name will be used as the machine's name, subsequent names will be
# aliased in your hosts file and in nginx
#
# (When overriding, include vagrant.local if you need it)
hosts:
    - mysite.local

# Site Configuration
# (When overriding, include all values)
site:
    name: My Site Name

# Plugins
#
# Install and activate a list of plugins from wp.org
plugins:
   - query-monitor

# Extensions
#
# Install a list of extensions automatically
extensions:
  - mailhog
  - xdebug
  - phpunit
  - tester

```

5. Do you have any Chassis other extensions installed? No
