### ISSUE TITLE
PHP 8.1 is installed but PHP 7.4 is specified in the local and main config file

### ISSUE THREAD

**Issue by addaeabeng** [Chassis/Chassis#956]
This has the added bonus of breaking Wordpress as it doesn't support php8 yet.

1. What operating system do you use?

Mac OS Big Sur

2. What version of Vagrant are you running?

2.2.16

3. Are you using VirtualBox or VMWare and which version are you using?

VirtualBox

4. Do you have a custom YAML file? If so, what does it contain?
   (Please paste in your `chassis.local.yaml` file)

```
paths:
    base: ..
    content: content
    wp: wordpress
hosts:
    - siemensworld.local

# Enable Multisite for MultilingualPress.
multisite: Yes

# Define database with a prefix, since we have tests as well.
database:
    name: wordpress
    user: wordpress
    password: vagrantpassword
    prefix: wp_

# Define the extensions we want.
extensions:
    - chassis/xdebug
    - chassis/sequelpro
    - chassis/mailhog
    - chassis/npm
    - chassis/chassis-openssl
    - shadyvb/chassis-redis
    - chassis/chassis_elasticsearch

# Set PHP version to 7.4 to align with hosting.
php: 7.4

elasticsearch:
    repo_version: '6.x'
    version: '6.3.2'`
```

5. Do you have any Chassis other extensions installed? If so, what are they?
