### ISSUE TITLE
Upgrading from 7.4 to 8.1 fails

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#980]
I needed to upgrade from PHP 7.4 on one of my installs today and I saw the following issue:
```
Warning: Unknown variable: 'packages'. (file: /vagrant/puppet/modules/chassis/manifests/php.pp, line: 67, column: 20)
```

My config was as follows:
```
hosts:
  - keepup.local
  - syd.keepup.local
  - yleague.keepup.local
  - bri.keepup.local
  - cbr.keepup.local
  - ccm.keepup.local
php: 8.1
multisite: true
extensions:
  - chassis/xdebug
  - chassis/mailhog
  - chassis/sequelpro
  # - chassis/phpunit
  - chassis/nodejs
  # - chassis/tester
  - chassis/npm
  - chassis/fish
  # - chassis/intl
  - chassis/imagick
  - chassis/gmagick
  - chassis/pretty_permalinks
  - chassis/phpmyadmin
  - chassis/vip_go
  - chassis/media_fallback
  - chassis/phpmyadmin
  - chassis/composer
permalink: '/%year%/%monthnum%/%day%/%postname%/'
media_fallback: 'https://backend.keepup.com.au/wp-content'
admin:
  user: username
  email: admin@example.com
  password: password
synced_folders:
  logs/nginx: /var/log/nginx
  logs/php: /var/log/php
# VirtualBox-specific customisations.
virtualbox:
    # Memory, in megabytes.
    #
    # (e.g. 1024)
    memory: 3072

    # CPU count.
    #
    # (e.g. 2)
    cpus: 4
phpunit:
  version: 7
```

To work around this I changed https://github.com/Chassis/Chassis/blob/main/puppet/modules/chassis/manifests/php.pp#L67 to be:
```
$core_packages = $common_packages
```

I'll need to do some testing with version switching before I do a PR and patch it and check the extensions for references of `$packages`
